import Sidebar from '@/components/shared/Sidebar';
import type { Metadata } from 'next';

export const metadata: Metadata = {
  title: '홈페이지',
  description: 'Generated by create next app',
};

export default function MainLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <>
      <div
        className='h-dvh transition-all duration-500  w-full 
      font-[family-name:var(--font-geist-sans)] flex min-w-fit'
      >
        <Sidebar />
        {children}
      </div>
    </>
  );
}
